# Generated by Django 3.2.5 on 2021-07-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaproductos'),
            preserve_default=False,
        ),
    ]
