# Generated by Django 3.2.5 on 2021-08-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210805_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img',
        ),
    ]
